name: AstralAntiVoid
version: '${project.version}'
main: ru.didirus.astralantivoid.AstralAntiVoid
api-version: 1.19
authors: [ didirus ]
softdepend:
  - Essentials
  - CMI
description: Simple plugin for prevent players into void
website: https://github.com/AstraliumMC
commands:
  aavreload:
    description: Reload main configuration file with Astralium Pooooweeeeeeer!
  aavset:
    description: Set spawn XYZ for AstralAntiVoid Teleportation
