name: AstralAntiVoid
version: '${project.version}'
main: ru.didirus.astralantivoidlobby.AstralAntiVoidLobby
api-version: 1.19
authors: [ didirus ]
softdepend:
  - Essentials
  - CMI
description: Simple plugin for prevent players into void
website: https://github.com/AstraliumMC
